# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mantis < Formula
  desc ""
  homepage "https://getaugur.ai"
  version "0.0.95"
  depends_on :macos

  on_intel do
    url "https://github.com/pranil-augur/mantis/releases/download/v0.0.95/mantis_0.0.95_darwin_amd64.tar.gz"
    sha256 "3e85c62ac182e313d0240f642aa7aeaa4141acde3ac6e974e631857776e76147"

    def install
      bin.install "mantis"
    end
  end
  on_arm do
    url "https://github.com/pranil-augur/mantis/releases/download/v0.0.95/mantis_0.0.95_darwin_arm64.tar.gz"
    sha256 "8f1c3162861d8c411e5805796a018e876a229634376d7d36001669c7b2d74fb2"

    def install
      bin.install "mantis"
    end
  end
end
