# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mantis < Formula
  desc ""
  homepage "https://getaugur.ai"
  version "0.9.5"
  depends_on :macos

  on_intel do
    url "https://mantis-public-releases.s3.us-east-2.amazonaws.com/mantis/v0.9.5/mantis_0.9.5_darwin_amd64.tar.gz"
    sha256 "22b0b18a82d93e511d0cd7d126b36ee60f8d64656425e4469101890e576f30e3"

    def install
      bin.install "mantis"
    end
  end
  on_arm do
    url "https://mantis-public-releases.s3.us-east-2.amazonaws.com/mantis/v0.9.5/mantis_0.9.5_darwin_arm64.tar.gz"
    sha256 "a016e5f36053762d52ee67198a9fdbf4c98f5d2924ef7e6d188e9f92c4a1a13a"

    def install
      bin.install "mantis"
    end
  end
end
